"""users update2

Revision ID: 275f1d8a0157
Revises: 5536bc46dff6
Create Date: 2022-04-04 20:27:20.733282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275f1d8a0157'
down_revision = '5536bc46dff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('in_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Books', 'in_stock')
    # ### end Alembic commands ###
