"""users update2

Revision ID: 5536bc46dff6
Revises: d7ad2cff0e41
Create Date: 2022-04-04 20:24:39.856852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5536bc46dff6'
down_revision = 'd7ad2cff0e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Books_author'), 'Books', ['author'], unique=False)
    op.create_index(op.f('ix_Books_id'), 'Books', ['id'], unique=False)
    op.create_index(op.f('ix_Books_title'), 'Books', ['title'], unique=False)
    op.drop_index('ix_leads_company', table_name='leads')
    op.drop_index('ix_leads_email', table_name='leads')
    op.drop_index('ix_leads_first_name', table_name='leads')
    op.drop_index('ix_leads_id', table_name='leads')
    op.drop_index('ix_leads_last_name', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='leads_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leads_pkey')
    )
    op.create_index('ix_leads_last_name', 'leads', ['last_name'], unique=False)
    op.create_index('ix_leads_id', 'leads', ['id'], unique=False)
    op.create_index('ix_leads_first_name', 'leads', ['first_name'], unique=False)
    op.create_index('ix_leads_email', 'leads', ['email'], unique=False)
    op.create_index('ix_leads_company', 'leads', ['company'], unique=False)
    op.drop_index(op.f('ix_Books_title'), table_name='Books')
    op.drop_index(op.f('ix_Books_id'), table_name='Books')
    op.drop_index(op.f('ix_Books_author'), table_name='Books')
    op.drop_table('Books')
    # ### end Alembic commands ###
