"""users update2

Revision ID: b57f2344931e
Revises: 275f1d8a0157
Create Date: 2022-04-04 20:34:48.446126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57f2344931e'
down_revision = '275f1d8a0157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
